version: '3.8'

services:
  spark-master:
    image: bitnami/spark:3.5.2
    container_name: spark-master
    hostname: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_DIRS=/tmp
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - spark-master-data:/tmp
    networks:
      - spark-network

  spark-worker-1:
    image: bitnami/spark:3.5.2
    container_name: spark-worker-1
    hostname: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=5g
      - SPARK_WORKER_CORES=3
      - SPARK_LOCAL_DIRS=/tmp
      - SPARK_WORKER_PORT=8081
      - SPARK_WORKER_WEBUI_PORT=8081
    ports:
      - "8081:8081"
    volumes:
      - spark-worker-1-data:/tmp
    networks:
      - spark-network


  spark-worker-2:
    image: bitnami/spark:3.5.2
    container_name: spark-worker-2
    hostname: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=5g
      - SPARK_WORKER_CORES=3
      - SPARK_LOCAL_DIRS=/tmp
      - SPARK_WORKER_PORT=8082
      - SPARK_WORKER_WEBUI_PORT=8082
    ports:
      - "8082:8082"
    volumes:
      - spark-worker-2-data:/tmp
    networks:
      - spark-network

  jupyter-notebook:
    image: jupyter/pyspark-notebook:latest
    container_name: jupyter-notebook
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
    ports:
      - "8888:8888"
    volumes:
      - ./work:/home/jovyan/work
    networks:
      - spark-network

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - spark-network

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
    networks:
      - spark-network
    
networks:
  spark-network:
    driver: bridge

volumes:
  spark-master-data:  # Defined volume for Spark master data
  spark-worker-1-data:  # Defined volume for Spark worker 1 data
  spark-worker-2-data:  # Defined volume for Spark worker 2 data